language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npm run semantic-release

notifications:
  email:
    - zyx@class62.cn